version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@cloud.cpaw4immyopw.us-east-1.rds.amazonaws.com:5432/postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

 # frontend:
 #   build:
 #     context: ./frontend
 #     dockerfile: Dockerfile
 #   ports:
 #     - "3000:3000"
 #   depends_on:
 #     backend:
#       condition: service_healthy
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:3000"]
#      interval: 10s
#      timeout: 5s
#      retries: 3
